@startuml
!theme cerulean

title Activity Diagram

start
:Користувач бажає вивчити інформацію про вологість;
:Програмний продукт відображає список тем, пов'язаних з вологістю;
:Користувач вибирає тему, яка його цікавить;
repeat
  if (Користувач обрав тему, яка його цікавить) then (так)
    :Програмний продукт відображає список інформацій по обраній темі;
    :Користувач вибирає інформацію;
    repeat
      if (Користувач обрав інформацію) then (так)
        :Програмний продукт надає більше деталей та можливостей реалізації по обраній інформації та темі;
      end
      else (ні)
        :Програмний продукт чекає, поки користувач вибере інформацію;
      endif
    repeat while (Користувач не обрав інформацію)
    end
  else (ні)
  :Програмний продукт чекає, поки Користувач вибере тему;
  endif
repeat while (Користувач не обрав тему, яка його цікавить)
end
@enduml
