@startuml
!theme cerulean
hide circle
title UML-ConceptClasses

Class Користувач{
    Ім'я
    Прізвище
}

Class "План мікроклімату"{
    Назва
    Аналіз потреб
    Параметри
    План виконання робіт
    Використаний шаблон
    Використана інформація
}

Class "Шаблон плану створення"{
    Назва
    Опис шаблону
    Аналіз потреб
    Параметри
    План виконання робіт
}

Користувач"1" --> "*""План мікроклімату": Отримує

"Шаблон плану створення""1" --> "1""План мікроклімату": "Використовується для створення"

@enduml
