# https://github.com/marketplace/actions/super-linter

name: Program Code Linter

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  ProgramCodeLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3
      - name: Lint Program Code
        uses: github/super-linter@v4
        env:
          VALIDATE_JAVA: true
          FILTER_REGEX_INCLUDE: ./.*\.java
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
